#include "Api.h"

INLINE_API_CALL bool Api_IsValidVehicle(int vehicleid);
INLINE_API_CALL float Api_GetVehicleDistanceFromPoint(int vehicleid, float x, float y, float z);
INLINE_API_CALL int Api_CreateVehicle(int vehicletype, float x, float y, float z, float rotation, int color1, int color2, int respawn_delay);
INLINE_API_CALL bool Api_DestroyVehicle(int vehicleid);
INLINE_API_CALL bool Api_IsVehicleStreamedIn(int vehicleid, int forplayerid);
INLINE_API_CALL bool Api_GetVehiclePos(int vehicleid, float *x, float *y, float *z);
INLINE_API_CALL bool Api_SetVehiclePos(int vehicleid, float x, float y, float z);
INLINE_API_CALL bool Api_GetVehicleZAngle(int vehicleid, float *z_angle);
INLINE_API_CALL bool Api_GetVehicleRotationQuat(int vehicleid, float *w, float *x, float *y, float *z);
INLINE_API_CALL bool Api_SetVehicleZAngle(int vehicleid, float z_angle);
INLINE_API_CALL bool Api_SetVehicleParamsForPlayer(int vehicleid, int playerid, bool objective, bool doorslocked);
INLINE_API_CALL bool Api_ManualVehicleEngineAndLights();
INLINE_API_CALL bool Api_SetVehicleParamsEx(int vehicleid, bool engine, bool lights, bool alarm, bool doors, bool bonnet, bool boot, bool objective);
INLINE_API_CALL bool Api_GetVehicleParamsEx(int vehicleid, bool *engine, bool *lights, bool *alarm, bool *doors, bool *bonnet, bool *boot, bool *objective);
INLINE_API_CALL bool Api_SetVehicleToRespawn(int vehicleid);
INLINE_API_CALL bool Api_LinkVehicleToInterior(int vehicleid, int interiorid);
INLINE_API_CALL bool Api_AddVehicleComponent(int vehicleid, int componentid);
INLINE_API_CALL bool Api_RemoveVehicleComponent(int vehicleid, int componentid);
INLINE_API_CALL bool Api_ChangeVehicleColor(int vehicleid, int color1, int color2);
INLINE_API_CALL bool Api_ChangeVehiclePaintjob(int vehicleid, int paintjobid);
INLINE_API_CALL bool Api_SetVehicleHealth(int vehicleid, float health);
INLINE_API_CALL bool Api_GetVehicleHealth(int vehicleid, float *health);
INLINE_API_CALL bool Api_AttachTrailerToVehicle(int trailerid, int vehicleid);
INLINE_API_CALL bool Api_DetachTrailerFromVehicle(int vehicleid);
INLINE_API_CALL bool Api_IsTrailerAttachedToVehicle(int vehicleid);
INLINE_API_CALL int Api_GetVehicleTrailer(int vehicleid);
INLINE_API_CALL bool Api_SetVehicleNumberPlate(int vehicleid, const char *numberplate);
INLINE_API_CALL int Api_GetVehicleModel(int vehicleid);
INLINE_API_CALL int Api_GetVehicleComponentInSlot(int vehicleid, int slot);
INLINE_API_CALL int Api_GetVehicleComponentType(int component);
INLINE_API_CALL bool Api_RepairVehicle(int vehicleid);
INLINE_API_CALL bool Api_GetVehicleVelocity(int vehicleid, float *X, float *Y, float *Z);
INLINE_API_CALL bool Api_SetVehicleVelocity(int vehicleid, float X, float Y, float Z);
INLINE_API_CALL bool Api_SetVehicleAngularVelocity(int vehicleid, float X, float Y, float Z);
INLINE_API_CALL bool Api_GetVehicleDamageStatus(int vehicleid, int *panels, int *doors, int *lights, int *tires);
INLINE_API_CALL bool Api_UpdateVehicleDamageStatus(int vehicleid, int panels, int doors, int lights, int tires);
INLINE_API_CALL bool Api_SetVehicleVirtualWorld(int vehicleid, int worldid);
INLINE_API_CALL int Api_GetVehicleVirtualWorld(int vehicleid);
INLINE_API_CALL bool Api_GetVehicleModelInfo(int model, int infotype, float *X, float *Y, float *Z);
