#include "Api.h"

INLINE_API_CALL bool Api_SetSpawnInfo(int playerid, int team, int skin, float x, float y, float z, float rotation, int weapon1, int weapon1_ammo, int weapon2, int weapon2_ammo, int weapon3, int weapon3_ammo);
INLINE_API_CALL bool Api_SpawnPlayer(int playerid);
INLINE_API_CALL bool Api_SetPlayerPos(int playerid, float x, float y, float z);
INLINE_API_CALL bool Api_SetPlayerPosFindZ(int playerid, float x, float y, float z);
INLINE_API_CALL bool Api_GetPlayerPos(int playerid, float *x, float *y, float *z);
INLINE_API_CALL bool Api_SetPlayerFacingAngle(int playerid, float angle);
INLINE_API_CALL bool Api_GetPlayerFacingAngle(int playerid, float *angle);
INLINE_API_CALL bool Api_IsPlayerInRangeOfPoint(int playerid, float range, float x, float y, float z);
INLINE_API_CALL float Api_GetPlayerDistanceFromPoint(int playerid, float x, float y, float z);
INLINE_API_CALL bool Api_IsPlayerStreamedIn(int playerid, int forplayerid);
INLINE_API_CALL bool Api_SetPlayerInterior(int playerid, int interiorid);
INLINE_API_CALL int Api_GetPlayerInterior(int playerid);
INLINE_API_CALL bool Api_SetPlayerHealth(int playerid, float health);
INLINE_API_CALL bool Api_GetPlayerHealth(int playerid, float *health);
INLINE_API_CALL bool Api_SetPlayerArmour(int playerid, float armour);
INLINE_API_CALL bool Api_GetPlayerArmour(int playerid, float *armour);
INLINE_API_CALL bool Api_SetPlayerAmmo(int playerid, int weaponid, int ammo);
INLINE_API_CALL int Api_GetPlayerAmmo(int playerid);
INLINE_API_CALL int Api_GetPlayerWeaponState(int playerid);
INLINE_API_CALL int Api_GetPlayerTargetPlayer(int playerid);
INLINE_API_CALL bool Api_SetPlayerTeam(int playerid, int teamid);
INLINE_API_CALL int Api_GetPlayerTeam(int playerid);
INLINE_API_CALL bool Api_SetPlayerScore(int playerid, int score);
INLINE_API_CALL int Api_GetPlayerScore(int playerid);
INLINE_API_CALL int Api_GetPlayerDrunkLevel(int playerid);
INLINE_API_CALL bool Api_SetPlayerDrunkLevel(int playerid, int level);
INLINE_API_CALL bool Api_SetPlayerColor(int playerid, int color);
INLINE_API_CALL int Api_GetPlayerColor(int playerid);
INLINE_API_CALL bool Api_SetPlayerSkin(int playerid, int skinid);
INLINE_API_CALL int Api_GetPlayerSkin(int playerid);
INLINE_API_CALL bool Api_GivePlayerWeapon(int playerid, int weaponid, int ammo);
INLINE_API_CALL bool Api_ResetPlayerWeapons(int playerid);
INLINE_API_CALL bool Api_SetPlayerArmedWeapon(int playerid, int weaponid);
INLINE_API_CALL bool Api_GetPlayerWeaponData(int playerid, int slot, int *weapon, int *ammo);
INLINE_API_CALL bool Api_GivePlayerMoney(int playerid, int money);
INLINE_API_CALL bool Api_ResetPlayerMoney(int playerid);
INLINE_API_CALL int Api_SetPlayerName(int playerid, const char *name);
INLINE_API_CALL int Api_GetPlayerMoney(int playerid);
INLINE_API_CALL int Api_GetPlayerState(int playerid);
INLINE_API_CALL bool Api_GetPlayerIp(int playerid, char *ip, int size);
INLINE_API_CALL int Api_GetPlayerPing(int playerid);
INLINE_API_CALL int Api_GetPlayerWeapon(int playerid);
INLINE_API_CALL bool Api_GetPlayerKeys(int playerid, int *keys, int *updown, int *leftright);
INLINE_API_CALL int Api_GetPlayerName(int playerid, char *name, int size);
INLINE_API_CALL bool Api_SetPlayerTime(int playerid, int hour, int minute);
INLINE_API_CALL bool Api_GetPlayerTime(int playerid, int *hour, int *minute);
INLINE_API_CALL bool Api_TogglePlayerClock(int playerid, bool toggle);
INLINE_API_CALL bool Api_SetPlayerWeather(int playerid, int weather);
INLINE_API_CALL bool Api_ForceClassSelection(int playerid);
INLINE_API_CALL bool Api_SetPlayerWantedLevel(int playerid, int level);
INLINE_API_CALL int Api_GetPlayerWantedLevel(int playerid);
INLINE_API_CALL bool Api_SetPlayerFightingStyle(int playerid, int style);
INLINE_API_CALL int Api_GetPlayerFightingStyle(int playerid);
INLINE_API_CALL bool Api_SetPlayerVelocity(int playerid, float x, float y, float z);
INLINE_API_CALL bool Api_GetPlayerVelocity(int playerid, float *x, float *y, float *z);
INLINE_API_CALL bool Api_PlayCrimeReportForPlayer(int playerid, int suspectid, int crime);
INLINE_API_CALL bool Api_PlayAudioStreamForPlayer(int playerid, const char *url, float posX, float posY, float posZ, float distance, bool usepos);
INLINE_API_CALL bool Api_StopAudioStreamForPlayer(int playerid);
INLINE_API_CALL bool Api_SetPlayerShopName(int playerid, const char *shopname);
INLINE_API_CALL bool Api_SetPlayerSkillLevel(int playerid, int skill, int level);
INLINE_API_CALL int Api_GetPlayerSurfingVehicleID(int playerid);
INLINE_API_CALL int Api_GetPlayerSurfingObjectID(int playerid);
INLINE_API_CALL bool Api_RemoveBuildingForPlayer(int playerid, int modelid, float fX, float fY, float fZ, float fRadius);
INLINE_API_CALL bool Api_GetPlayerLastShotVectors(int playerid, float *fOriginX, float *fOriginY, float *fOriginZ, float *fHitPosX, float *fHitPosY, float *fHitPosZ);
INLINE_API_CALL bool Api_SetPlayerAttachedObject(int playerid, int index, int modelid, int bone, float fOffsetX, float fOffsetY, float fOffsetZ, float fRotX, float fRotY, float fRotZ, float fScaleX, float fScaleY, float fScaleZ, int materialcolor1, int materialcolor2);
INLINE_API_CALL bool Api_RemovePlayerAttachedObject(int playerid, int index);
INLINE_API_CALL bool Api_IsPlayerAttachedObjectSlotUsed(int playerid, int index);
INLINE_API_CALL bool Api_EditAttachedObject(int playerid, int index);
INLINE_API_CALL int Api_CreatePlayerTextDraw(int playerid, float x, float y, const char *text);
INLINE_API_CALL bool Api_PlayerTextDrawDestroy(int playerid, int text);
INLINE_API_CALL bool Api_PlayerTextDrawLetterSize(int playerid, int text, float x, float y);
INLINE_API_CALL bool Api_PlayerTextDrawTextSize(int playerid, int text, float x, float y);
INLINE_API_CALL bool Api_PlayerTextDrawAlignment(int playerid, int text, int alignment);
INLINE_API_CALL bool Api_PlayerTextDrawColor(int playerid, int text, int color);
INLINE_API_CALL bool Api_PlayerTextDrawUseBox(int playerid, int text, bool use);
INLINE_API_CALL bool Api_PlayerTextDrawBoxColor(int playerid, int text, int color);
INLINE_API_CALL bool Api_PlayerTextDrawSetShadow(int playerid, int text, int size);
INLINE_API_CALL bool Api_PlayerTextDrawSetOutline(int playerid, int text, int size);
INLINE_API_CALL bool Api_PlayerTextDrawBackgroundColor(int playerid, int text, int color);
INLINE_API_CALL bool Api_PlayerTextDrawFont(int playerid, int text, int font);
INLINE_API_CALL bool Api_PlayerTextDrawSetProportional(int playerid, int text, bool set);
INLINE_API_CALL bool Api_PlayerTextDrawSetSelectable(int playerid, int text, bool set);
INLINE_API_CALL bool Api_PlayerTextDrawShow(int playerid, int text);
INLINE_API_CALL bool Api_PlayerTextDrawHide(int playerid, int text);
INLINE_API_CALL bool Api_PlayerTextDrawSetString(int playerid, int text, const char *string);
INLINE_API_CALL bool Api_PlayerTextDrawSetPreviewModel(int playerid, int text, int modelindex);
INLINE_API_CALL bool Api_PlayerTextDrawSetPreviewRot(int playerid, int text, float fRotX, float fRotY, float fRotZ, float fZoom);
INLINE_API_CALL bool Api_PlayerTextDrawSetPreviewVehCol(int playerid, int text, int color1, int color2);
INLINE_API_CALL bool Api_SetPVarInt(int playerid, const char *varname, int value);
INLINE_API_CALL int Api_GetPVarInt(int playerid, const char *varname);
INLINE_API_CALL bool Api_SetPVarString(int playerid, const char *varname, const char *value);
INLINE_API_CALL bool Api_GetPVarString(int playerid, const char *varname, char *value, int size);
INLINE_API_CALL bool Api_SetPVarFloat(int playerid, const char *varname, float value);
INLINE_API_CALL float Api_GetPVarFloat(int playerid, const char *varname);
INLINE_API_CALL bool Api_DeletePVar(int playerid, const char *varname);
INLINE_API_CALL int Api_GetPVarsUpperIndex(int playerid);
INLINE_API_CALL bool Api_GetPVarNameAtIndex(int playerid, int index, char *varname, int size);
INLINE_API_CALL int Api_GetPVarType(int playerid, const char *varname);
INLINE_API_CALL bool Api_SetPlayerChatBubble(int playerid, const char *text, int color, float drawdistance, int expiretime);
INLINE_API_CALL bool Api_PutPlayerInVehicle(int playerid, int vehicleid, int seatid);
INLINE_API_CALL int Api_GetPlayerVehicleID(int playerid);
INLINE_API_CALL int Api_GetPlayerVehicleSeat(int playerid);
INLINE_API_CALL bool Api_RemovePlayerFromVehicle(int playerid);
INLINE_API_CALL bool Api_TogglePlayerControllable(int playerid, bool toggle);
INLINE_API_CALL bool Api_PlayerPlaySound(int playerid, int soundid, float x, float y, float z);
INLINE_API_CALL bool Api_ApplyAnimation(int playerid, const char *animlib, const char *animname, float fDelta, bool loop, bool lockx, bool locky, bool freeze, int time, bool forcesync);
INLINE_API_CALL bool Api_ClearAnimations(int playerid, bool forcesync);
INLINE_API_CALL int Api_GetPlayerAnimationIndex(int playerid);
INLINE_API_CALL bool Api_GetAnimationName(int index, char *animlib, int animlib_size, char *animname, int animname_size);
INLINE_API_CALL int Api_GetPlayerSpecialAction(int playerid);
INLINE_API_CALL bool Api_SetPlayerSpecialAction(int playerid, int actionid);
INLINE_API_CALL bool Api_SetPlayerCheckpoint(int playerid, float x, float y, float z, float size);
INLINE_API_CALL bool Api_DisablePlayerCheckpoint(int playerid);
INLINE_API_CALL bool Api_SetPlayerRaceCheckpoint(int playerid, int type, float x, float y, float z, float nextx, float nexty, float nextz, float size);
INLINE_API_CALL bool Api_DisablePlayerRaceCheckpoint(int playerid);
INLINE_API_CALL bool Api_SetPlayerWorldBounds(int playerid, float x_max, float x_min, float y_max, float y_min);
INLINE_API_CALL bool Api_SetPlayerMarkerForPlayer(int playerid, int showplayerid, int color);
INLINE_API_CALL bool Api_ShowPlayerNameTagForPlayer(int playerid, int showplayerid, bool show);
INLINE_API_CALL bool Api_SetPlayerMapIcon(int playerid, int iconid, float x, float y, float z, int markertype, int color, int style);
INLINE_API_CALL bool Api_RemovePlayerMapIcon(int playerid, int iconid);
INLINE_API_CALL bool Api_AllowPlayerTeleport(int playerid, bool allow);
INLINE_API_CALL bool Api_SetPlayerCameraPos(int playerid, float x, float y, float z);
INLINE_API_CALL bool Api_SetPlayerCameraLookAt(int playerid, float x, float y, float z, int cut);
INLINE_API_CALL bool Api_SetCameraBehindPlayer(int playerid);
INLINE_API_CALL bool Api_GetPlayerCameraPos(int playerid, float *x, float *y, float *z);
INLINE_API_CALL bool Api_GetPlayerCameraFrontVector(int playerid, float *x, float *y, float *z);
INLINE_API_CALL int Api_GetPlayerCameraMode(int playerid);
INLINE_API_CALL float Api_GetPlayerCameraAspectRatio(int playerid);
INLINE_API_CALL float Api_GetPlayerCameraZoom(int playerid);
INLINE_API_CALL bool Api_AttachCameraToObject(int playerid, int objectid);
INLINE_API_CALL bool Api_AttachCameraToPlayerObject(int playerid, int playerobjectid);
INLINE_API_CALL bool Api_InterpolateCameraPos(int playerid, float FromX, float FromY, float FromZ, float ToX, float ToY, float ToZ, int time, int cut);
INLINE_API_CALL bool Api_InterpolateCameraLookAt(int playerid, float FromX, float FromY, float FromZ, float ToX, float ToY, float ToZ, int time, int cut);
INLINE_API_CALL bool Api_IsPlayerConnected(int playerid);
INLINE_API_CALL bool Api_IsPlayerInVehicle(int playerid, int vehicleid);
INLINE_API_CALL bool Api_IsPlayerInAnyVehicle(int playerid);
INLINE_API_CALL bool Api_IsPlayerInCheckpoint(int playerid);
INLINE_API_CALL bool Api_IsPlayerInRaceCheckpoint(int playerid);
INLINE_API_CALL bool Api_SetPlayerVirtualWorld(int playerid, int worldid);
INLINE_API_CALL int Api_GetPlayerVirtualWorld(int playerid);
INLINE_API_CALL bool Api_EnableStuntBonusForPlayer(int playerid, bool enable);
INLINE_API_CALL bool Api_EnableStuntBonusForAll(bool enable);
INLINE_API_CALL bool Api_TogglePlayerSpectating(int playerid, bool toggle);
INLINE_API_CALL bool Api_PlayerSpectatePlayer(int playerid, int targetplayerid, int mode);
INLINE_API_CALL bool Api_PlayerSpectateVehicle(int playerid, int targetvehicleid, int mode);
INLINE_API_CALL bool Api_StartRecordingPlayerData(int playerid, int recordtype, const char *recordname);
INLINE_API_CALL bool Api_StopRecordingPlayerData(int playerid);
INLINE_API_CALL bool Api_CreateExplosionForPlayer(int playerid, float X, float Y, float Z, int type, float Radius);
